---
builds:
  - binary: circleci-config-merge
    main: cmd/circleci-config-merge/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  prerelease: true
archives:
  - format_overrides:
      - goos: windows
        format: zip
brews:
  -
    # NOTE: make sure the url_template, the token and given repo (github or gitlab) owner and name are from the
    # same kind. We will probably unify this in the next major version like it is done with scoop.

    # GitHub/GitLab repository to push the formula to
    repository:
      owner: suzuki-shunsuke
      name: homebrew-circleci-config-merge
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    # Your app's homepage.
    # Default is empty.
    homepage: https://github.com/suzuki-shunsuke/circleci-config-merge

    # Template of your app's description.
    # Default is empty.
    description: Generate .circleci/config.yml by merging multiple files
    license: MIT

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: auto

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/circleci-config-merge --version"

signs:
  - cmd: cosign
    artifacts: checksum
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    output: true
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign-blob
      - --output-signature
      - ${signature}
      - --output-certificate
      - ${certificate}
      - --oidc-provider
      - github
      - ${artifact}

winget:
  - publisher: suzuki-shunsuke
    short_description: Generate .circleci/config.yml by merging multiple files
    license: mit

    # Publisher URL.
    #
    # Templates: allowed
    # publisher_url: https://goreleaser.com

    publisher_support_url: https://github.com/suzuki-shunsuke/circleci-config-merge/issues

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    #
    # Default: v1
    # goamd64: v1

    # URL which is determined by the given Token (github, gitlab or gitea).
    #
    # Default depends on the client.
    # Templates: allowed
    url_template: "https://github.com/suzuki-shunsuke/circleci-config-merge/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # commit_author:
    #   name: Shunsuke Suzuki
    #   email: suzuki.shunsuke.1989@gmail.com

    # The project name and current git tag are used in the format string.
    #
    # Templates: allowed
    # commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"

    # Path for the file inside the repository.
    #
    # Default: manifests/<lowercased first char of publisher>/<publisher>/<version>
    # path: manifests/g/goreleaser/1.19

    homepage: https://github.com/suzuki-shunsuke/circleci-config-merge

    # Your app's long description.
    #
    # Templates: allowed
    description: Generate .circleci/config.yml by merging multiple files.

    # License URL.
    #
    # Templates: allowed
    license_url: https://github.com/suzuki-shunsuke/circleci-config-merge/blob/main/LICENSE

    # Copyright.
    #
    # Templates: allowed
    # copyright: ""

    # Copyright URL.
    #
    # Templates: allowed
    # copyright_url: ""

    # Setting this will prevent goreleaser to actually try to commit the updated
    # package - instead, it will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    #
    # If set to auto, the release will not be uploaded to the repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    #
    # Templates: allowed
    skip_upload: true

    # Release notes.
    #
    # If you want to use the release notes generated by GoReleaser, use
    # `{{.Changelog}}` as the value.
    #
    # Templates: allowed
    # release_notes: "{{.Changelog}}"

    # Release notes URL.
    #
    # Templates: allowed
    release_notes_url: https://github.com/suzuki-shunsuke/circleci-config-merge/releases/tag/{{.Tag}}

    # Tags.
    tags:
      - circleci

    # Repository to push the generated files to.
    # repository:
    #   owner: suzuki-shunsuke
    #   # owner: mini-core
    #   name: winget-pkgs

    #   # Optionally a branch can be provided.
    #   #
    #   # Default: default repository branch
    #   # Templates: allowed
    #   branch: "circleci-config-merge-{{.Version}}"

    #   # Sets up pull request creation instead of just pushing to the given branch.
    #   # Make sure the 'branch' property is different from base before enabling
    #   # it.
    #   #
    #   # Since: v1.17
    #   pull_request:
    #     # Whether to enable it or not.
    #     enabled: true

    #     # Whether to open the PR as a draft or not.
    #     #
    #     # Since: v1.19
    #     draft: true

    #     # Base can also be another repository, in which case the owner and name
    #     # above will be used as HEAD, allowing cross-repository pull requests.
    #     #
    #     # Since: v1.19
    #     base:
    #       owner: microsoft
    #       # owner: mini-core
    #       name: winget-pkgs

chocolateys:
  - owners: Shunsuke Suzuki

    # The app's title.
    # A human-friendly title of the package.
    #
    # Default: ProjectName
    # title: Test Chocolatey Package by GoReleaser

    # Your app's authors (probably you).
    authors: Shunsuke Suzuki

    # Your app's project url.
    # It is a required field.
    project_url: https://github.com/suzuki-shunsuke/circleci-config-merge

    # URL which is determined by the given Token (github,
    # gitlab or gitea).
    #
    # Default: depends on the git remote
    # Templates: allowed
    # url_template: "https://github.com/foo/bar/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # App's icon.
    icon_url: https://github.com/suzuki-shunsuke.png

    # Your app's copyright details.
    copyright: 2020 Shunsuke Suzuki

    # App's license information url.
    license_url: https://github.com/suzuki-shunsuke/circleci-config-merge/blob/main/LICENSE

    # Your apps's require license acceptance:
    # Specify whether the client must prompt the consumer to accept the package
    # license before installing.
    require_license_acceptance: false

    # Your app's source url.
    project_source_url: https://github.com/suzuki-shunsuke/circleci-config-merge

    # Your app's documentation url.
    docs_url: https://github.com/suzuki-shunsuke/circieci-config-merge/blob/main/README.md

    # App's bugtracker url.
    bug_tracker_url: https://github.com/suzuki-shunsuke/circieci-config-merge/issues

    # Your app's tag list.
    # tags: "goreleaser go test"

    # Your app's summary:
    summary: Generate .circleci/config.yml by merging multiple files

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      circleci-config-merge generates .circleci/config.yml by merging multiple files.

    # Your app's release notes.
    # A description of the changes made in this release of the package.
    # Supports markdown. To prevent the need to continually update this field,
    # providing a URL to an external list of Release Notes is perfectly
    # acceptable.
    release_notes: "https://github.com/suzuki-shunsuke/circleci-config-merge/releases/tag/v{{ .Version }}"

    # App's dependencies
    # The version is not required.
    # dependencies:
    #   - id: go
    #     version: 1.20.0

    # The api key that should be used to push to the chocolatey repository.
    #
    # WARNING: do not expose your api key in the configuration file!
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

    # The source repository that will push the package to.
    source_repo: "https://push.chocolatey.org/"

    # Setting this will prevent goreleaser to actually try to push the package
    # to chocolatey repository, leaving the responsibility of publishing it to
    # the user.
    skip_publish: false

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    #
    # Default: 'v1'
    # goamd64: v1
