commands:
  foo:
    steps:
      - run:
          name: foo
          command: echo foo
executors:
  foo:
    docker:
      - image: alpine:3.14.2
workflows:
  build:
    jobs:
      - foo
  foo:
    jobs:
      - foo
jobs:
  foo:
    executor: foo
    steps:
      - foo
