---
name: Release
on:
  push:
    tags: [v*]
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@feat/chocolatey
    with:
      homebrew: true
      go-version: 1.21.0
      aqua_version: v2.16.4
      winget_base_repo: microsoft/winget-pkgs
      winget_head_repo: suzuki-shunsuke/winget-pkgs
      winget_new: false
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
      github_token_for_winget: ${{secrets.WINGET_ACCESS_TOKEN}}
      chocolatey_api_key: ${{secrets.CHOCOLATEY_API_KEY}}
    permissions:
      contents: write
      id-token: write
      actions: read
