---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@b00b650f092aaa9e748caa01d96ab380cf8348b5 # v0.2.1
    with:
      aqua_policy_config: aqua-policy.yaml
      homebrew: true
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      contents: write
      id-token: write
      actions: read
