---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@5f97504fee36e24636d22b12f10e3e343f14f0ae # v0.2.2
    with:
      aqua_policy_config: aqua-policy.yaml
      homebrew: true
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      contents: write
      id-token: write
      actions: read
