---
name: Release
on:
  push:
    tags: [v*]
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@feat-add-winget_github_token
    with:
      homebrew: true
      go-version: 1.21.4
      aqua_version: v2.17.2
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
      winget_github_token: ${{secrets.WINGET_ACCESS_TOKEN}}
    permissions:
      contents: write
      id-token: write
      actions: read
