---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@feat/chocolatey
    with:
      homebrew: true
      go-version: 1.21.0
      aqua_version: v2.10.1
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
      winget_github_token: ${{secrets.MINICORE_ACCESS_TOKEN}}
    permissions:
      contents: write
      id-token: write
      actions: read
