---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@256b1eef8f90d2877ee6c56dfae7e1e4f658272e # v0.2.0
    with:
      aqua_policy_config: aqua-policy.yaml
      homebrew: true
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      contents: write
      id-token: write
      actions: read
