name: renovate-config-validator

permissions: {}

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json

jobs:
  renovate-config-validator:
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@1a2fd7b15d99b1c434124b0bd2d8bd55b54ed869 # v0.2.0
    permissions:
      contents: read
