---
name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17.5'

    - uses: aquaproj/aqua-installer@v1.0.0
      with:
        aqua_version: v1.5.0

    - name: golangci-lint
      run: golangci-lint run

    - name: test
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        bash ci/test.sh circleci-config-merge

    - name: Generate token
      id: generate_token
      if: startsWith(github.ref, 'refs/tags/')
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: remove changes
      # Sometimes it is failed to release by goreleaser due to changes of go.sum
      run: git checkout -- .
    - name: fetch tags to release
      run: git fetch --tags
    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

    - name: Run GoReleaser (skip publish)
      uses: goreleaser/goreleaser-action@v2
      if: "! startsWith(github.ref, 'refs/tags/')"
      with:
        version: latest
        args: release --rm-dist --snapshot
